# Generated by Django 5.0.2 on 2024-02-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("device_group", "0001_initial"),
        ("firmware_info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("scheduled_date", models.DateTimeField(default=None, null=True)),
                ("completion_date", models.DateTimeField(default=None, null=True)),
                (
                    "firmware",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="firmware_info.firmwareinfo",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="device_group.devicegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
