# Generated by Django 5.0.2 on 2024-02-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_group", "0002_alter_devicegroup_id"),
        ("tag", "0002_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="device_group.devicegroup",
            ),
            preserve_default=False,
        ),
    ]
