version: "3.8"

include:
  - elk.yaml

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  authDB:
    image: postgres:15.3
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth_db
    ports:
      - "5431:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  lotaDB:
    image: postgres:15.3
    container_name: films_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lota
      POSTGRES_PASSWORD: lota
      POSTGRES_DB: lota_db
    ports:
      - "5432:5432"
    volumes:
      - lota_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U films -d films_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0.11
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  auth_db:
  lota_db:
