# Generated by Django 5.0.2 on 2024-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="devices", to="tag.tag"
            ),
        ),
    ]
