# Generated by Django 5.0.2 on 2024-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="state",
            field=models.IntegerField(
                choices=[
                    (2, "Planned"),
                    (3, "Pending"),
                    (4, "Running"),
                    (5, "Completed"),
                    (1, "Failed"),
                ]
            ),
        ),
    ]
