# Generated by Django 5.0.2 on 2024-02-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0001_initial"),
        ("deployment_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymenttask",
            name="deployment",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployment_tasks",
                to="deployment.deployment",
            ),
            preserve_default=False,
        ),
    ]
