# Generated by Django 5.0.2 on 2024-02-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("deployment_task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLogRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deployment_task.deploymenttask",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
